### ISSUE TITLE
Support GPT-2 Large model 

### ISSUE THREAD

**Issue by causten** [ROCmSoftwarePlatform/AMDMIGraphX#1215]
Getting an error.  Possibly need to add some parameters to get it to work?

 /opt/rocm/bin/migraphx-driver perf gpt2_large_1_fp16_gpu.onnx
Compiling ...
Reading: ./onnx_models/gpt2_large_1_fp16_gpu/gpt2_large_1_fp16_gpu.onnx
module: "main"
main:@0 = check_context::migraphx::version_1::gpu::context -> float_type, {}, {}
main:@1 = hip::hip_allocate_memory[shape=float_type, {8960}, {1},id=main:scratch] -> float_type, {8960}, {1}
main:@2 = hip::hip_copy_literal[id=main:@literal:1] -> half_type, {1, 1, 1280}, {1280, 1280, 1}
main:@3 = load[offset=0,end=4](main:@1) -> float_type, {1, 1}, {1, 1}
input_ids = @param:input_ids -> int64_type, {1, 1}, {1, 1}
...
main:@2844 = @return(main:@2843)

Allocating params ...
Running performance report ...
:0:rocdevice.cpp            :2614: 1286029213690 us: 26907: [tid:0x7f7bdff97700] Device::callbackQueue aborting with error : HSA_STATUS_ERROR_MEMORY_FAULT: Agent attempted to access an inaccessible address. code: 0x2b
Aborted (core dumped)

**Comment by causten** [comment]
I built the onnx file via a bnechmakring script in ORT.  All the --disable's may not be needed.  
/workspace/benchmarking# python3 /workspace/onnxruntime/build/Release/onnxruntime/transformers/benchmark.py -g -m gpt2-large --sequence_length 384  --batch_sizes 1 --provider=migraphx -p fp16  --disable_gelu --disable_layer_norm --disable_attention --disable_skip_layer_norm --disable_embed_layer_norm --disable_bias_skip_layer_norm --disable_bias_gelu

**Comment by causten** [comment]
main:@3060 = @return(main:@3059)
/opt/rocm/bin/migraphx-driver perf ./onnx_models/gpt2_large_1_fp16_gpu/gpt2_large_1_fp16_gpu.onnx
...
Allocating params ...
Running performance report ...
Memory access fault by GPU node-1 (Agent handle: 0x1b6e180) on address 0x7f4763fff000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)


Another example of the failure from a RX6800xt

**Comment by kahmed10** [comment]
What are the input params to this model? Have you tried using --fill1 on them?

**Comment by causten** [comment]
Thanks this works! 
migraphx-driver run ./gpt2_large_1.onnx  --fill1 input_ids
